---
title: "Year_cleaning_test"
output: html_document
---

```{r}
#| warning: false
#| message: false
library(tidyverse)
library(tidymodels)
library(knitr)
library(pROC)
library(ggplot2)
library(patchwork)
library(dplyr)
library(plotly)
library(bslib)
library(googlesheets4)
```


```{r}
#| message: false
Year_test <- read_csv("/Users/lauren/Desktop/agroecology/raw_data/Master Harvest Log - Main.csv")
```

```{r}
#| warning: false
#| message: false
Year_test_clean <- Year_test |>
  na.omit() |> #gets rid of NA values
  mutate(
    Cost = as.numeric(gsub("\\$", "", Cost)),
    Monthly = paste(month(Date, label = TRUE, abbr = TRUE), Year)#removing dollar sign
  ) |>
  mutate(
    Date = as.Date(Date, format = "%m/%d/%Y"), #changing variable type of date variable
    Bimonthly = case_when(
      day(Date) <= 15 ~ paste("Early", month(Date, label = TRUE, abbr = TRUE), Year),
      day(Date) > 15  ~ paste("Late", month(Date, label = TRUE, abbr = TRUE), Year)
    ), #creates the bimonthly variable to be formatted as 'Early/Late' + 'Month Abbreviation'
    Bimonthly = factor(Bimonthly, levels = unique(Bimonthly[order(Date)]))
  ) |>
  group_by(Year, Bimonthly, Vegetable) |>
  mutate(Bimonthly_Cost = sum(Cost, na.rm = TRUE),
         Bimonthly_Quantity = sum(Quantity, na.rm = TRUE)) |>
  ungroup() |>
  
  group_by(Year, Monthly, Vegetable) |>
  # adding total cost + quantity per vegetable per monthly period
  mutate(Monthly_Cost = sum(Cost, na.rm = TRUE),
         Monthly_Quantity = sum(Quantity, na.rm = TRUE)) |>
  ungroup() |>
  
  group_by(Year, Vegetable) |>
  mutate(
    Year_Quantity = sum(Quantity, na.rm = TRUE),
    Year_Cost = sum(Cost, na.rm = TRUE)
  ) |>
  ungroup()
```

